# .travis.yml for dycone

language: r
warnings_are_errors: true
sudo: false

env:
 global:
    - CRAN: http://cran.rstudio.com
apt_packages:
    - libcurl4-openssl-dev
    - libssl-dev libgmp-dev
r_github_packages:
    - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
