# .travis.yml for dycone

language: r
warnings_are_errors: true
sudo: true

env:
 global:
    - CRAN: http://cran.rstudio.com
apt_packages:
    - libcurl4-openssl-dev
    - libssl-dev libgmp-dev
r_github_packages:
    - jimhester/covr
bioc_packages:
    - limma
    - BiocCheck
after_success:
    - Rscript -e "BiocCheck::BiocCheck('.')"
    - Rscript -e 'library(covr);codecov()'
