# .travis.yml for dycone

language: R

sudo: false

cache: packages

addons:
    apt:
        sources:
            - r-packages-precise
        packages:
            - libgmp-dev
            - libglpk-dev

bioc_required: true
bioc_packages:
    - BiocInstaller
    - BiocCheck
r_packages:
    - rmarkdown

after_success:
    - Rscript -e 'covr::codecov()'
